version: "3.7"

services:
  # Mysql 8.0
  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
volumes:
  database:

networks:
    backend:
        driver: bridge
