# Database Configuration
spring:
  # disable default security
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/database?useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  flyway:
    enabled: true
    user: user
    password: password
    encoding: UTF-8
    url: jdbc:mysql://localhost:3306/database?useSSL=false
    locations: classpath:db/migration
    baseline-on-migrate: true
